---
- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true

- name: Install Homebrew packages
  community.general.homebrew:
    name: "{{ brew_packages }}"
    state: present
  when: brew_packages | length > 0

- name: Install Homebrew casks
  community.general.homebrew_cask:
    name: "{{ brew_casks }}"
    state: present
  when: brew_casks | length > 0
