---
- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true

- name: Upgrade all Homebrew packages
  community.general.homebrew:
    upgrade_all: true

- name: Install Homebrew packages
  community.general.homebrew:
    name: "{{ brew_packages }}"
    state: present
  when: brew_packages | length > 0
  register: brew_result

- ansible.builtin.debug:
    var: brew_result.changed_pkgs

- name: Install Homebrew casks
  community.general.homebrew_cask:
    name: "{{ brew_casks }}"
    state: present
  when: brew_casks | length > 0
  register: cask_result

- ansible.builtin.debug:
    var: cask_result.msg
