---
- name: Ensure ZDOTDIR exists
  file:
    path: "{{ zdotdir }}"
    state: directory
    owner: "{{ ansible_user_id | default(ansible_user) }}"
    group: staff
    mode: "0755"

- name: Install zshenv in home directory
  template:
    src: roles/common/templates/managed_file.j2
    dest: "{{ ansible_env.HOME }}/.zshenv"
    owner: "{{ ansible_user_id | default(ansible_user) }}"
    group: staff
    mode: "0644"
  vars:
    source_file: "dot-zshenv"

- name: Install zsh configuration files in ZDOTDIR
  template:
    src: roles/common/templates/managed_file.j2
    dest: "{{ zdotdir }}/{{ item.dest }}"
    owner: "{{ ansible_user_id | default(ansible_user) }}"
    group: staff
    mode: "0644"
  loop:
    - { source_file: "dot-zshrc", dest: ".zshrc" }
    - { source_file: "dot-zprofile", dest: ".zprofile" }
  loop_control:
    loop_var: item
  vars:
    source_file: "{{ item.source_file }}"
