- name: Ensure ZDOTDIR exists
  file:
    path: "{{ zdotdir }}"
    state: directory
    owner: "{{ ansible_user_id | default(ansible_user) }}"
    group: staff
    mode: "0755"

- name: Deploy .zshenv to home
  copy:
    content: |
      {{ managed_by_comment }}

      {{ lookup('file', 'dot-zshenv') }}
    dest: "{{ ansible_env.HOME }}/.zshenv"
    owner: "{{ ansible_user_id | default(ansible_user) }}"
    group: staff
    mode: "0644"

- name: Deploy ZSH configuration files to ZDOTDIR
  copy:
    content: |
      {{ managed_by_comment }}

      {{ lookup('file', 'dot-' + item.filename | replace('.', '')) }}
    dest: "{{ zdotdir }}/{{ item.filename }}"
    owner: "{{ ansible_user_id | default(ansible_user) }}"
    group: staff
    mode: "0644"
  loop:
    - { filename: .zshrc }
    - { filename: .zprofile }
