---
- name: Check if SDKMAN is installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.sdkman/bin/sdkman-init.sh"
  register: sdkman_installed

- name: Install SDKMAN
  ansible.builtin.shell: |
    curl -s "https://get.sdkman.io?ci=true" | bash
  args:
    creates: "{{ ansible_env.HOME }}/.sdkman/bin/sdkman-init.sh"
  when: not sdkman_installed.stat.exists
