promptToReturnFromSubprocess: false
disableStartupPopups: true
quitOnTopLevelReturn: true
git:
  commitPrefix:
    - pattern: "^\\w+\\/(\\w+-\\d+).*"
      replace: "[$1] "
  paging:
    colorArg: always
    pager: delta --dark --paging=never --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
os:
  editPreset: nvim
gui:
  nerdFontsVersion: "3"
