---
common_brew_packages:
  - bat
  - eza
  - fd
  - fzf
  - git
  - git-delta
  - jq
  - just
  - lazydocker
  - lazygit
  - neovim
  - pipx
  - ripgrep
  - starship
  - stow
  - yazi
  - zoxide
  - zsh

common_brew_casks:
  - ghostty
