---
common_brew_packages:
  - fd
  - git
  - jq
  - just
  - neovim
  - pipx
  - ripgrep
  - zsh
  - stow
  - bat
  - fzf
  - eza
  - zoxide
  - git-delta
  - starship
  - lazygit
  - lazydocker

common_brew_casks:
  - ghostty
