---
- hosts: all
  become: false
  gather_facts: true
  vars:
    brew_packages: "{{ common_brew_packages + host_brew_packages | default([]) }}"
    brew_casks: "{{ common_brew_casks + host_brew_casks | default([]) }}"
  roles:
    - role: sdkman
      when: install_sdkman | default(false) | bool
  tasks:
    - name: Update Homebrew
      community.general.homebrew:
        update_homebrew: true

    - name: Install Homebrew packages
      community.general.homebrew:
        name: "{{ brew_packages }}"
        state: present

    - name: Install Homebrew casks
      community.general.homebrew_cask:
        name: "{{ brew_casks }}"
        state: present
