---
- name: Configure macOS machine with Homebrew packages
  hosts: localhost
  become: false
  vars:
    brew_packages:
      - fd
      - git
      - jq
      - just
      - pipx
      - ripgrep
      - zsh
    brew_casks:
      - ghostty
  tasks:
    - name: Ensure required Homebrew packages are installed
      community.general.homebrew:
        name: "{{ brew_packages }}"
        state: present
        update_homebrew: true

    - name: Ensure required Homebrew casks are installed
      community.general.homebrew_cask:
        name: "{{ brew_casks }}"
        state: present
