---
- hosts: all
  become: false
  gather_facts: true
  vars:
    brew_packages: "{{ common_brew_packages + host_brew_packages | default([]) }}"
    brew_casks: "{{ common_brew_casks + host_brew_casks | default([]) }}"
  roles:
    - role: homebrew
      when: (brew_packages | length > 0) or (brew_casks | length > 0)
    - role: sdkman
      when: install_sdkman | default(false) | bool
