---
- name: Configure macOS machine with Homebrew packages
  hosts: localhost
  become: false
  vars:
    brew_packages:
      - fd
      - ripgrep
      - jq
  tasks:
    - name: Ensure required Homebrew packages are installed
      community.general.homebrew:
        name: "{{ item }}"
        state: present
        update_homebrew: true
      loop: "{{ brew_packages }}"
